"""Train a minimal ADM-vs-PanIN image-level baseline on current repo data."""

from __future__ import annotations

import argparse
import csv
from collections import Counter
from pathlib import Path

from pancreas_vision.data import discover_records, split_records
from experiment_runner import load_split_csv, run_experiment


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train a minimal ADM-vs-PanIN image-level baseline on current repo data."
    )
    parser.add_argument("--data-root", type=Path, default=Path("data"))
    parser.add_argument("--metadata-csv", type=Path, default=Path("data/2.csv"))
    parser.add_argument("--output-dir", type=Path, default=Path("artifacts/baseline"))
    parser.add_argument("--epochs", type=int, default=8)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--image-size", type=int, default=224)
    parser.add_argument("--learning-rate", type=float, default=1e-4)
    parser.add_argument("--test-size", type=float, default=0.3)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--num-workers", type=int, default=2)
    parser.add_argument(
        "--split-csv",
        type=Path,
        default=None,
        help="Optional fixed bag-level split CSV generated by build_split_protocol.py.",
    )
    parser.add_argument(
        "--include-multichannel",
        action="store_true",
        help="Include multichannel_adm and multichannel_kc_adm as authoritative labels.",
    )
    parser.add_argument(
        "--exclude-kpc",
        action="store_true",
        help="Exclude the KPC folder if you want a stricter PanIN proxy based only on KC.",
    )
    parser.add_argument(
        "--freeze-backbone",
        action="store_true",
        help="Freeze the pretrained ResNet18 backbone and train only the classifier head.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    records = discover_records(
        args.data_root,
        include_kpc=not args.exclude_kpc,
        include_multichannel=args.include_multichannel,
        metadata_csv=args.metadata_csv,
    )
    records = [record for record in records if record.sample_type == "whole_image"]

    if args.split_csv is None:
        train_records, test_records = split_records(
            records,
            test_size=args.test_size,
            random_seed=args.seed,
        )
    else:
        split_lookup = load_split_csv(args.split_csv)
        filtered_records = [record for record in records if record.lesion_id in split_lookup]
        train_records = [
            record for record in filtered_records if split_lookup[record.lesion_id] == "train"
        ]
        test_records = [
            record for record in filtered_records if split_lookup[record.lesion_id] == "test"
        ]

    run_experiment(
        train_records=train_records,
        test_records=test_records,
        output_dir=args.output_dir,
        model_name="resnet18",
        model_kwargs={"freeze_backbone": args.freeze_backbone},
        epochs=args.epochs,
        batch_size=args.batch_size,
        image_size=args.image_size,
        learning_rate=args.learning_rate,
        seed=args.seed,
        num_workers=args.num_workers,
        compute_bag_metrics=True,
        extra_summary={
            "arguments": {
                "data_root": args.data_root.as_posix(),
                "output_dir": args.output_dir.as_posix(),
                "metadata_csv": args.metadata_csv.as_posix(),
                "epochs": args.epochs,
                "batch_size": args.batch_size,
                "image_size": args.image_size,
                "learning_rate": args.learning_rate,
                "test_size": args.test_size,
                "seed": args.seed,
                "num_workers": args.num_workers,
                "split_csv": None if args.split_csv is None else args.split_csv.as_posix(),
                "include_multichannel": args.include_multichannel,
                "exclude_kpc": args.exclude_kpc,
                "freeze_backbone": args.freeze_backbone,
            },
            "record_counts": {
                "total": len(records),
                "train": len(train_records),
                "test": len(test_records),
            },
        },
    )


if __name__ == "__main__":
    main()